### PR TITLE
GH action extended

### LINKED ISSUE #21: Fix MinGW build
At the moment MinGW can build a .dll but that .dll cannot be loaded by Notepad++

### PR DESCRIPTION
**Pull request by chcg**
- added arm64 build
- gh action update check via dependabot
- added gh mingw build + fix #21

### CODE REVIEW

**Comment by ffes** [comment]
Thanks for the PR.

I have tried the fix for the Makefile and it worked. Thanks a lot for that!

Although I am not a big fan of adding very different things in one PR, thanks for adding the ARM64 build.

I have added the ARM64 compilers to Visual Studio and that seems to work. But I have no way to check if that works. I don't have a Windows ARM64 device.

And I have a couple of questions:

Why have you added the gh action `dependabot`?
The project doesn't have any dependencies it can check as far as I am aware of. The only external dependency are SQLite and the NPP headers. But all those files are just copied into the repository. So I don't see any need to add dependabot.

Why is the MinGW-build added to `msbuild.yml` and not added as a separate `mingw-build.yml`?

And looking at the YML the `BITS=${{ matrix.build_platform }}` is not gonna work. I would suggest to change it to something like this (note that I haven't tested this):
```yml
- name: build x86
  if: matrix.build_platform == '32'
  run: make ARCH=x86_64-w64-mingw32

- name: build x64
  if: matrix.build_platform == '64'
  run: make ARCH=i686-w64-mingw32
```

**Comment by chcg** [comment]
- dependabot checks for updated github actions, e.g. if there is a newer version of actions/checkout@v2
- the mingw build could be splitted into an extra yml file, in my repos it is just named CI_build.yml and therefore I was blind to spot the different file names, corrected that
- missed to add the variable bits to the makefile, modifying ARCH from the yml is also an option

**Comment by ffes** [comment]
Apart from the small change I requested in the Makefile the PR looks good to me.

**Comment by chcg** [comment]
adapted gh action and makefile to your suggestion

**Comment by ffes** [comment]
Thanks again for the PR

**Pull request merged**
